---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/master/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
#
xpack.license.self_generated.type: trial
xpack.security.enabled: true

## OpenNLP models for English
## see https://github.com/spinscale/elasticsearch-ingest-opennlp
ingest.opennlp.model.file.persons: /usr/share/elasticsearch/en-ner-persons.bin
ingest.opennlp.model.file.dates: /usr/share/elasticsearch/en-ner-locations.bin
ingest.opennlp.model.file.locations: /usr/share/elasticsearch/en-ner-dates.bin
