image:
    file: .gitpod.dockerfile

tasks:
  - name: Start Elastic stack in background
    command: |
      docker compose -f docker-compose.yml up
      gp sync-done stack
  - name: Configure python
    init: |
      export PIP_USER=false
      pip install --upgrade pip
      sed -i "s/include-system-site-packages = false/include-system-site-packages = true/" /home/gitpod/.pyenv/versions/lab/pyvenv.cfg;
      pip install -r requirements.txt
    
# ports:
#   - port: 9200
#     onOpen: ignore
#     visibility: private

vscode:
  extensions:
    - eamodio.gitlens
    - ria.elastic
    - ms-python.python
    - ms-python.anaconda-extension-pack
    - ms-azuretools.vscode-docker
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
