tasks:
  - name: Start Elasticsearch in background
    command: docker run -p 9200:9200 bitnami/elasticsearch:8.3.3
  - name: Configure python
    init: |
      pyenv shell
      export PIP_USER=false
      pyenv virtualenv lab
      sed -i "s/include-system-site-packages = false/include-system-site-packages = true/" /home/gitpod/.pyenv/versions/lab/pyvenv.cfg;
      pyenv activate lab
      python -m pip install --upgrade pip
      pip install -r requirements.txt

ports:
  - port: 9200
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - eamodio.gitlens
    - ria.elastic
    - ms-python.python
    - ms-python.anaconda-extension-pack
    - ms-azuretools.vscode-docker
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
