tasks:
  - name: Start Elasticsearch in background
    # init: docker pull bitnami/elasticsearch:8.3.3
    command: docker run -p 9200:9200 bitnami/elasticsearch:8.3.3
  - name: Configure python
    init: |
      pyenv virtualenv venv
      pyenv activate venv
      python -m pip install --upgrade pip
      pip install -r requirements.txt

ports:
  - port: 9200
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - eamodio.gitlens
    - ria.elastic
    - ms-python.python
    - ms-python.anaconda-extension-pack
    - ms-azuretools.vscode-docker
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
