tasks:
  - name: Start Elasticsearch in background
    init: docker pull bitnami/elasticsearch:8.1.2
    command: docker run bitnami/elasticsearch:8.1.2

ports:
  - port: 9200
    onOpen: open-preview
    visibility: private

vscode:
  extensions:
    - eamodio.gitlens
    - ms-python.python
    - ms-python.anaconda-extension-pack
    - ms-azuretools.vscode-docker
    - hashicorp.terraform
    - ms-toolsai.jupyter
    - ria.elastic
