tasks:
  - name: Start Elasticsearch in background
    init: docker pull bitnami/elasticsearch:8.1.2
    command: docker run bitnami/elasticsearch:8.1.2
  - name: Install Python dependencies
    init: pip install -r requirements.txt

ports:
  - port: 9200
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - eamodio.gitlens
    - ms-python.python
    - ms-python.anaconda-extension-pack
    - ms-azuretools.vscode-docker
    - ms-toolsai.jupyter
    - ria.elastic
